name: Build & Deploy Server (Production)

on:
  push:
    branches:
      - main
    paths:
      - "packages/apps/server/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "nlw-copa"
          heroku_email: "fellipeutaka@gmail.com"
          appdir: "packages/apps/server"
