name: Build & Deploy Server (Production)

on:
  push:
    branches:
      - main
    paths:
      - "packages/apps/server/**"
      - ".github/workflows/server-production.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "nlw-copa"
          heroku_email: "fellipeutaka@gmail.com"
          procfile: "web: yarn workspace @nlw-copa/server start"
        env:
          HD_APP_BASE: "packages/apps/server"
